### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by jbants** [stactools-packages/spot#3]
The package should be renamed since it is a subset of SPOT data.

This dataset is from the legacy geobase project. It now is referenced through https://open.canada.ca/data/en/dataset/d799c202-603d-4e5c-b1eb-d058803f80f9

Suggest the name change to `nrcan_spot_ortho`

**Comment by jamesvrt** [comment]
I've altered the repo contents to reflect the name change (#2) but I don't have the permission required to change the repo name.

**Comment by gadomski** [comment]
I can do the rename, @jamesvrt can you confirm that `nrcan_spot_ortho` works?

**Comment by jamesvrt** [comment]
`nrcan-spot-ortho` would better fit the naming scheme of other packages

**Comment by gadomski** [comment]
Renamed to `nrcan-spot-ortho`.
